spring:
  task:
    scheduling:
      thread-name-prefix: limits-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: admin
    password: secret
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: "/limit-app"
  port: 8083

limits:
  default-daily-limit: 10000.00
  reset-cron: "0 0 0 * * ?"

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  enabled: true